language: ruby

rvm:
  - 2.3.1

branches:
  only:
    - development

script:
  - "[ -d build ] && rm -r build"
  - "bundle exec middleman build"
  - "bundle exec middleman deploy"

notifications:
  email: false
