language: ruby

cache: bundler

rvm:
  - 2.3.1

branches:
  only:
    - development

env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL="contact@travis-ci.com"

script:
  - bundle exec rake travis:script

after_success:
  - bundle exec rake travis:after_success
