baseurl: ""
url: "https://henry40408.github.io"

title: Henry Wu
description: >
  I am software engineer in Taipei, currently work in Hahow, mostly building things with Ruby on Rails and Node.js applications. I also work on a bunch of projects on GitHub.
date_format: "%B %d %Y"
github_username:  henry40408

markdown: kramdown
highlighter: none
permalink: /:year/:month/:title.html
theme: minima

disqus:
  shortname: henry40408
google_analytics: UA-6529501-15

picture:
  source: "assets/images/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5]
      attr:
        class: "ui image picture"
      source_small:
        media: "(max-width: 32rem)"
        width: "414"
      source_medium:
        media: "(max-width: 64rem)"
        width: "768"
      source_default:
        width: "1440"
      
tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

exclude:
  - circle.yml
  - circle_deploy.sh
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
