baseurl: ""
url: "henry40408.github.io"

title: Henry Wu
description: >
  I am software engineer in Taipei, currently work in Hahow, mostly building things with Ruby on Rails and Node.js applications. I also work on a bunch of projects on GitHub.
github_username:  henry40408

markdown: kramdown
permalink: /:year/:month/:title.html
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
