baseURL = 'https://henry40408.com'
languageCode = 'en-us'
title = "Heng-Yi Wu's BLOG"
theme = 'PaperMod'
enableEmoji = true
relativeURLs = true

[menus]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'

[params]
author = 'henry40408'
favicon = 'favicon.ico'

[[params.ananke_socials]]
name = 'github'
url = 'https://github.com/henry40408'
weight = 10

[[params.ananke_socials]]
name = 'mastodon'
url = 'https://mastodon.social/@henry40408'
weight = 20
