version: 2

jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - vendor/bundle
      - run: |
          git config user.email 'sayhi@circleci.com'
          git config user.name 'CircleCI'
      - run: npm run deploy
